# Generated by Django 5.1.4 on 2025-11-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="is_sensed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="habit",
            name="negative_score",
            field=models.IntegerField(
                default=0,
                help_text="Score added if this habit is checked (for bad habits) or missed. Usually 0 or negative (e.g., -1).",
            ),
        ),
    ]
