# Generated by Django 5.1.4 on 2025-11-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0002_quote_is_sensed_alter_habit_negative_score"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quote",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="quote",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
